#+TITLE:     Chapter 2: Visualize and Compare
#+AUTHOR:    Emmanuel A. Garcia
#+EMAIL:     egarcia@ohlone.edu
#+DESCRIPTION: In class assignment
#+INCLUDE:"~/macro.org"

You recently collected data in a survey. Students filled out their
student ID, class, whether they were registered to vote, GPA, and favorite
type of pet. You are interested in comparing and contrasting the
responses by class and analyzing the overall distribution.

You can find the data in
"MATH-159_Chapter-2_Visualize-and-compare.csv". Complete the tasks
below in groups and turn in one electronic copy per group. Groups are
5 or smaller. Make sure you note how you accomplished the task with
statcrunch "Stat -> tables -> ..." and what information you entered
and buttons pressed.

1. Make frequency and relative frequency tables for all of the
   variables except GPA and ID. Also write down the results for the
   table themselves.
2. Make barplots for the all the variables except GPA and ID. Make a
   histogram for for GPA.
3. Describe the distributions.
4. Make two way tables for "Class" and "Pet", and "Class" and
   "Registered". Also write down the results for the tables
   themselves. Are there any interesting associations between the
   values?
5. Make stacked barplots for the 2 two way tables above.
6. How similar is the overall distribution for "Pet" to the
   distribution broken down according to "Class"?
